### ISSUE TITLE
Cannot set property 'abbr' of undefined

### ISSUE THREAD

**Issue by lukasoppermann** [zestedesavoir/zmarkdown#425]
Hey, I am getting the following error:

> TypeError: Cannot set property 'abbr' of undefined
    at Function.plugin (/Users/lukasoppermann/Repos/veare-next/node_modules/remark-abbr/dist/index.js:139:25)
    at freeze (/Users/lukasoppermann/Repos/veare-next/node_modules/unified/index.js:128:28)
    at Function.processSync (/Users/lukasoppermann/Repos/veare-next/node_modules/unified/index.js:394:5)
    at parseMarkdown (webpack-internal:///./lib/getMarkdown.ts:49:374)
    at getMarkdownBySlug (webpack-internal:///./lib/getMarkdown.ts:68:22)
    at eval (webpack-internal:///./lib/getMarkdown.ts:84:9)
    at Array.map (<anonymous>)
    at getAllMarkdown (webpack-internal:///./lib/getMarkdown.ts:80:86)
    at getStaticPaths (webpack-internal:///./pages/blog/[slug].tsx:36:90)
    at buildStaticPaths (/Users/lukasoppermann/Repos/veare-next/node_modules/next/dist/build/utils.js:16:86) {
  type: 'TypeError'

Is this an issue with remark@13 or am I doing something wrong?

**Comment by StaloneLab** [comment]
Currently, our plugins do not work with remark >= 13 which implement the new micromark plugin system internally.
While we intend to switch to the new system, no due date has been planned, and it requires a significant amount of work (as this repo contains a lot of plugins).
